//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavajaSuiza_.NET10.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavajaSuiza_.NET10.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        internal static string FlashlightActionOffText {
            get {
                return ResourceManager.GetString("FlashlightActionOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prender.
        /// </summary>
        internal static string FlashlightActionOnText {
            get {
                return ResourceManager.GetString("FlashlightActionOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota: La pantalla usará el máximo brillo para simular luz.
        /// </summary>
        internal static string FlashlightNoteText {
            get {
                return ResourceManager.GetString("FlashlightNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string FlashlightOpFlashText {
            get {
                return ResourceManager.GetString("FlashlightOpFlashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantalla.
        /// </summary>
        internal static string FlashlightOpScreenText {
            get {
                return ResourceManager.GetString("FlashlightOpScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige tu fuente de luz.
        /// </summary>
        internal static string FlashlightOptionsText {
            get {
                return ResourceManager.GetString("FlashlightOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luz de la Pantalla.
        /// </summary>
        internal static string FlashlightScreenLightText {
            get {
                return ResourceManager.GetString("FlashlightScreenLightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encendido.
        /// </summary>
        internal static string FlashlightStatusOffText {
            get {
                return ResourceManager.GetString("FlashlightStatusOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagado.
        /// </summary>
        internal static string FlashlightStatusOnText {
            get {
                return ResourceManager.GetString("FlashlightStatusOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linterna.
        /// </summary>
        internal static string FlashlightText {
            get {
                return ResourceManager.GetString("FlashlightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuadre.
        /// </summary>
        internal static string FramingText {
            get {
                return ResourceManager.GetString("FramingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string ManualText {
            get {
                return ResourceManager.GetString("ManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batería.
        /// </summary>
        internal static string MenuBateryText {
            get {
                return ResourceManager.GetString("MenuBateryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenamiento.
        /// </summary>
        internal static string MenuStorageText {
            get {
                return ResourceManager.GetString("MenuStorageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrónomo.
        /// </summary>
        internal static string MetronomeText {
            get {
                return ResourceManager.GetString("MetronomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string NotesText {
            get {
                return ResourceManager.GetString("NotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar idioma.
        /// </summary>
        internal static string SelectLanguageText {
            get {
                return ResourceManager.GetString("SelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia entre tema claro y oscuro.
        /// </summary>
        internal static string ThemeContentText {
            get {
                return ResourceManager.GetString("ThemeContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detener.
        /// </summary>
        internal static string TunerActionOffText {
            get {
                return ResourceManager.GetString("TunerActionOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajo.
        /// </summary>
        internal static string TunerBassText {
            get {
                return ResourceManager.GetString("TunerBassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charango.
        /// </summary>
        internal static string TunerCharangoText {
            get {
                return ResourceManager.GetString("TunerCharangoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4 = 440 Hz.
        /// </summary>
        internal static string TunerNoteText {
            get {
                return ResourceManager.GetString("TunerNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nailon.
        /// </summary>
        internal static string TunerNylonText {
            get {
                return ResourceManager.GetString("TunerNylonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Instrumento.
        /// </summary>
        internal static string TunerOptionsText {
            get {
                return ResourceManager.GetString("TunerOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acero.
        /// </summary>
        internal static string TunerSteelText {
            get {
                return ResourceManager.GetString("TunerSteelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afinador.
        /// </summary>
        internal static string TunerText {
            get {
                return ResourceManager.GetString("TunerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukelele.
        /// </summary>
        internal static string TunerUkeleleText {
            get {
                return ResourceManager.GetString("TunerUkeleleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violín.
        /// </summary>
        internal static string TunerViolinText {
            get {
                return ResourceManager.GetString("TunerViolinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clima.
        /// </summary>
        internal static string WeatherText {
            get {
                return ResourceManager.GetString("WeatherText", resourceCulture);
            }
        }
    }
}
