//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavajaSuiza_.NET10.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavajaSuiza_.NET10.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para mejor precisión evita conectar a fuentes de energía y mantente alejado de elementos magnéticos.
        /// </summary>
        internal static string CompassAdviceText {
            get {
                return ResourceManager.GetString("CompassAdviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección Cardinal.
        /// </summary>
        internal static string CompassCardinalAddressText {
            get {
                return ResourceManager.GetString("CompassCardinalAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTE.
        /// </summary>
        internal static string CompassCardinalEastText {
            get {
                return ResourceManager.GetString("CompassCardinalEastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string CompassCardinalEText {
            get {
                return ResourceManager.GetString("CompassCardinalEText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORESTE.
        /// </summary>
        internal static string CompassCardinalNorthEastText {
            get {
                return ResourceManager.GetString("CompassCardinalNorthEastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTE.
        /// </summary>
        internal static string CompassCardinalNorthText {
            get {
                return ResourceManager.GetString("CompassCardinalNorthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOROESTE.
        /// </summary>
        internal static string CompassCardinalNorthWestText {
            get {
                return ResourceManager.GetString("CompassCardinalNorthWestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string CompassCardinalNText {
            get {
                return ResourceManager.GetString("CompassCardinalNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURESTE.
        /// </summary>
        internal static string CompassCardinalSouthEastText {
            get {
                return ResourceManager.GetString("CompassCardinalSouthEastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUR.
        /// </summary>
        internal static string CompassCardinalSouthText {
            get {
                return ResourceManager.GetString("CompassCardinalSouthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUROESTE.
        /// </summary>
        internal static string CompassCardinalSouthWestText {
            get {
                return ResourceManager.GetString("CompassCardinalSouthWestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string CompassCardinalSText {
            get {
                return ResourceManager.GetString("CompassCardinalSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OESTE.
        /// </summary>
        internal static string CompassCardinalWestText {
            get {
                return ResourceManager.GetString("CompassCardinalWestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string CompassCardinalWText {
            get {
                return ResourceManager.GetString("CompassCardinalWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano ✅.
        /// </summary>
        internal static string CompassStatusAText {
            get {
                return ResourceManager.GetString("CompassStatusAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligeramente Inclinado ⚠️.
        /// </summary>
        internal static string CompassStatusBText {
            get {
                return ResourceManager.GetString("CompassStatusBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinado ⚠️⚠️.
        /// </summary>
        internal static string CompassStatusCText {
            get {
                return ResourceManager.GetString("CompassStatusCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Inclinado ❌.
        /// </summary>
        internal static string CompassStatusDText {
            get {
                return ResourceManager.GetString("CompassStatusDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical ❌❌.
        /// </summary>
        internal static string CompassStatusEText {
            get {
                return ResourceManager.GetString("CompassStatusEText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brújula.
        /// </summary>
        internal static string CompassText {
            get {
                return ResourceManager.GetString("CompassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        internal static string FlashlightActionOffText {
            get {
                return ResourceManager.GetString("FlashlightActionOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prender.
        /// </summary>
        internal static string FlashlightActionOnText {
            get {
                return ResourceManager.GetString("FlashlightActionOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota: La pantalla usará el máximo brillo para simular luz.
        /// </summary>
        internal static string FlashlightNoteText {
            get {
                return ResourceManager.GetString("FlashlightNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string FlashlightOpFlashText {
            get {
                return ResourceManager.GetString("FlashlightOpFlashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantalla.
        /// </summary>
        internal static string FlashlightOpScreenText {
            get {
                return ResourceManager.GetString("FlashlightOpScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige tu fuente de luz.
        /// </summary>
        internal static string FlashlightOptionsText {
            get {
                return ResourceManager.GetString("FlashlightOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luz de la Pantalla.
        /// </summary>
        internal static string FlashlightScreenLightText {
            get {
                return ResourceManager.GetString("FlashlightScreenLightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encendido.
        /// </summary>
        internal static string FlashlightStatusOffText {
            get {
                return ResourceManager.GetString("FlashlightStatusOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagado.
        /// </summary>
        internal static string FlashlightStatusOnText {
            get {
                return ResourceManager.GetString("FlashlightStatusOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linterna.
        /// </summary>
        internal static string FlashlightText {
            get {
                return ResourceManager.GetString("FlashlightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Horizontal) Paisaje.
        /// </summary>
        internal static string FramingAspectRatioLandscapeText {
            get {
                return ResourceManager.GetString("FramingAspectRatioLandscapeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Vertical) Retrato.
        /// </summary>
        internal static string FramingAspectRatioPortraitText {
            get {
                return ResourceManager.GetString("FramingAspectRatioPortraitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Cuadrado).
        /// </summary>
        internal static string FramingAspectRatioSquareText {
            get {
                return ResourceManager.GetString("FramingAspectRatioSquareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Vertical) Historias.
        /// </summary>
        internal static string FramingAspectRatioStoriesText {
            get {
                return ResourceManager.GetString("FramingAspectRatioStoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negro.
        /// </summary>
        internal static string FramingBackgroundBlackText {
            get {
                return ResourceManager.GetString("FramingBackgroundBlackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difuminar.
        /// </summary>
        internal static string FramingBackgroundBlurText {
            get {
                return ResourceManager.GetString("FramingBackgroundBlurText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanco.
        /// </summary>
        internal static string FramingBackgroundWhiteText {
            get {
                return ResourceManager.GetString("FramingBackgroundWhiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string FramingBtnGuardarText {
            get {
                return ResourceManager.GetString("FramingBtnGuardarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetear.
        /// </summary>
        internal static string FramingBtnResetText {
            get {
                return ResourceManager.GetString("FramingBtnResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contener.
        /// </summary>
        internal static string FramingModeContainText {
            get {
                return ResourceManager.GetString("FramingModeContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubrir.
        /// </summary>
        internal static string FramingModeCoverText {
            get {
                return ResourceManager.GetString("FramingModeCoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llenar.
        /// </summary>
        internal static string FramingModeFillText {
            get {
                return ResourceManager.GetString("FramingModeFillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuadre.
        /// </summary>
        internal static string FramingText {
            get {
                return ResourceManager.GetString("FramingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar Imagen.
        /// </summary>
        internal static string FramingUploadImageText {
            get {
                return ResourceManager.GetString("FramingUploadImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string ManualText {
            get {
                return ResourceManager.GetString("ManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batería.
        /// </summary>
        internal static string MenuBateryText {
            get {
                return ResourceManager.GetString("MenuBateryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenamiento.
        /// </summary>
        internal static string MenuStorageText {
            get {
                return ResourceManager.GetString("MenuStorageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad.
        /// </summary>
        internal static string MetronomeSpeedText {
            get {
                return ResourceManager.GetString("MetronomeSpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrónomo.
        /// </summary>
        internal static string MetronomeText {
            get {
                return ResourceManager.GetString("MetronomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string NotesText {
            get {
                return ResourceManager.GetString("NotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar idioma.
        /// </summary>
        internal static string SelectLanguageText {
            get {
                return ResourceManager.GetString("SelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia entre tema claro y oscuro.
        /// </summary>
        internal static string ThemeContentText {
            get {
                return ResourceManager.GetString("ThemeContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detener.
        /// </summary>
        internal static string TunerActionOffText {
            get {
                return ResourceManager.GetString("TunerActionOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajo.
        /// </summary>
        internal static string TunerBassText {
            get {
                return ResourceManager.GetString("TunerBassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charango.
        /// </summary>
        internal static string TunerCharangoText {
            get {
                return ResourceManager.GetString("TunerCharangoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4 = 440 Hz.
        /// </summary>
        internal static string TunerNoteText {
            get {
                return ResourceManager.GetString("TunerNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nailon.
        /// </summary>
        internal static string TunerNylonText {
            get {
                return ResourceManager.GetString("TunerNylonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Instrumento.
        /// </summary>
        internal static string TunerOptionsText {
            get {
                return ResourceManager.GetString("TunerOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acero.
        /// </summary>
        internal static string TunerSteelText {
            get {
                return ResourceManager.GetString("TunerSteelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afinador.
        /// </summary>
        internal static string TunerText {
            get {
                return ResourceManager.GetString("TunerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukelele.
        /// </summary>
        internal static string TunerUkeleleText {
            get {
                return ResourceManager.GetString("TunerUkeleleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violín.
        /// </summary>
        internal static string TunerViolinText {
            get {
                return ResourceManager.GetString("TunerViolinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clima.
        /// </summary>
        internal static string WeatherText {
            get {
                return ResourceManager.GetString("WeatherText", resourceCulture);
            }
        }
    }
}
